# Generated by Django 5.0.1 on 2024-02-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ithackgame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet',
            new_name='comment',
        ),
    ]
