# Generated by Django 5.0.1 on 2024-02-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithackgame', '0005_alter_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('free', 'free'), ('pc', 'pc'), ('moblie', 'moblie'), ('embed', 'embed'), ('anti', 'anti')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
