# Generated by Django 5.0.1 on 2024-02-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithackgame', '0006_board_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('free', 'free1'), ('pc', 'pc'), ('moblie', 'moblie'), ('embed', 'embed'), ('anti', 'anti')], max_length=50),
        ),
    ]
