# Generated by Django 5.0.1 on 2024-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithackgame', '0007_alter_board_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('free', '자유게시판'), ('pc', 'pc 게임'), ('moblie', '모바일 게임'), ('embed', '임베디드 게임'), ('anti', '안티포렌식')], max_length=50),
        ),
    ]
