# Generated by Django 5.0.1 on 2024-02-03 13:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithackgame', '0008_alter_board_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
    ]
