# Generated by Django 5.0.1 on 2024-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ithackgame', '0009_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
