# Generated by Django 5.0.1 on 2024-02-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ithackgame', '0010_notice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='user',
            new_name='name',
        ),
    ]
